//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ContactList
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private ContactList() : base("LightSwitchApplication:ContactList")
        {
            global::LightSwitchApplication.ContactList.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static ContactList CreateInstance()
        {
            return new global::LightSwitchApplication.ContactList(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void ContactsSet_SelectionChanged();

        partial void ContactsSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactsSet_Loaded(bool succeeded);

        partial void Prisoner_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prisoner_Loaded(bool succeeded);

        /// <summary>
        /// Gets the ContactsSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Contacts> ContactsSet
        {
            get
            {
                return global::LightSwitchApplication.ContactList.DetailsClass.GetValue(this, global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties.ContactsSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactsSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Prisoner Prisoner
        {
            get
            {
                return global::LightSwitchApplication.ContactList.DetailsClass.GetValue(this, global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties.Prisoner);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Prisoner_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.ContactList.DetailsClass.PropertySet, global::LightSwitchApplication.ContactList.DetailsClass.CommandSet, global::LightSwitchApplication.ContactList.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties.ContactsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>.Entry
                __ContactListEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>.Entry(
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeSavingEvent,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeSavedEvent,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeClosingEvent,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeCreated,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeActivated,
                    global::LightSwitchApplication.ContactList.DetailsClass.__ContactList_InvokeSaveErrorEvent);
            private static void __ContactList_InvokeInitializeDataWorkspace(global::LightSwitchApplication.ContactList s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.ContactList_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __ContactList_InvokeSavingEvent(global::LightSwitchApplication.ContactList s)
            {
                bool handled = false;
                s.ContactList_Saving(ref handled);
                return handled;
            }
            private static void __ContactList_InvokeSavedEvent(global::LightSwitchApplication.ContactList s)
            {
                s.ContactList_Saved();
            }
            private static bool __ContactList_InvokeClosingEvent(global::LightSwitchApplication.ContactList s)
            {
                bool cancel = false;
                s.ContactList_Closing(ref cancel);
                return cancel;
            }
            private static void __ContactList_InvokeCreated(global::LightSwitchApplication.ContactList s)
            {
                s.ContactList_Created();
            }
            private static void __ContactList_InvokeActivated(global::LightSwitchApplication.ContactList s)
            {
                s.ContactList_Activated();
            }
            private static bool __ContactList_InvokeSaveErrorEvent(global::LightSwitchApplication.ContactList s, global::System.Exception ex)
            {
                bool handled = false;
                s.ContactList_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.ContactList.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.ContactList.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.ContactList.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ContactsSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.ContactsSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts>.Data _ContactsSet;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner>.Data _Prisoner;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts> ContactsSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts>)base.GetItem(global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties.ContactsSet);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner> Prisoner
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner>)base.GetItem(global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties.Prisoner);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts>.Entry
                    ContactsSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts>.Entry(
                        "ContactsSet",
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_Stub,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_Validate,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_CreateQuery,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_SelectionChanged,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_OnCollectionChanged,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._ContactsSet_OnLoaded);
                private static void _ContactsSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContactList.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Contacts>.Data> c, global::LightSwitchApplication.ContactList.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactsSet, sf);
                }
                private static void _ContactsSet_Validate(global::LightSwitchApplication.ContactList s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.ContactsSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _ContactsSet_CreateQuery(global::LightSwitchApplication.ContactList.DetailsClass d, object[] args)
                {
                    return d.ContactsSetQuery();
                }
                private static void _ContactsSet_SelectionChanged(global::LightSwitchApplication.ContactList s)
                {
                    s.ContactsSet_SelectionChanged();
                }
                private static void _ContactsSet_OnCollectionChanged(global::LightSwitchApplication.ContactList s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.ContactsSet_Changed(e);
                }
                private static void _ContactsSet_OnLoaded(global::LightSwitchApplication.ContactList s, bool succeeded)
                {
                    s.ContactsSet_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner>.Entry
                    Prisoner = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner>.Entry(
                        "Prisoner",
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._Prisoner_Stub,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._Prisoner_Validate,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._Prisoner_CreateQuery,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._Prisoner_OnValueChanged,
                        global::LightSwitchApplication.ContactList.DetailsClass.PropertySetProperties._Prisoner_OnLoaded);
                private static void _Prisoner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContactList.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.ContactList, global::LightSwitchApplication.ContactList.DetailsClass, global::LightSwitchApplication.Prisoner>.Data> c, global::LightSwitchApplication.ContactList.DetailsClass d, object sf)
                {
                    c(d, ref d._Prisoner, sf);
                }
                private static void _Prisoner_Validate(global::LightSwitchApplication.ContactList s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Prisoner_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Prisoner_CreateQuery(global::LightSwitchApplication.ContactList.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Prisoner_OnValueChanged(global::LightSwitchApplication.ContactList s)
                {
                    s.Prisoner_Changed();
                }

                private static void _Prisoner_OnLoaded(global::LightSwitchApplication.ContactList s, bool succeeded)
                {
                    s.Prisoner_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ContactTypesList
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private ContactTypesList() : base("LightSwitchApplication:ContactTypesList")
        {
            global::LightSwitchApplication.ContactTypesList.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static ContactTypesList CreateInstance()
        {
            return new global::LightSwitchApplication.ContactTypesList(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesList_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void ContactTypesSet_SelectionChanged();

        partial void ContactTypesSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the ContactTypesSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.ContactTypes> ContactTypesSet
        {
            get
            {
                return global::LightSwitchApplication.ContactTypesList.DetailsClass.GetValue(this, global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties.ContactTypesSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactTypesSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySet, global::LightSwitchApplication.ContactTypesList.DetailsClass.CommandSet, global::LightSwitchApplication.ContactTypesList.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties.ContactTypesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>.Entry
                __ContactTypesListEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>.Entry(
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeSavingEvent,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeSavedEvent,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeClosingEvent,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeCreated,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeActivated,
                    global::LightSwitchApplication.ContactTypesList.DetailsClass.__ContactTypesList_InvokeSaveErrorEvent);
            private static void __ContactTypesList_InvokeInitializeDataWorkspace(global::LightSwitchApplication.ContactTypesList s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.ContactTypesList_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __ContactTypesList_InvokeSavingEvent(global::LightSwitchApplication.ContactTypesList s)
            {
                bool handled = false;
                s.ContactTypesList_Saving(ref handled);
                return handled;
            }
            private static void __ContactTypesList_InvokeSavedEvent(global::LightSwitchApplication.ContactTypesList s)
            {
                s.ContactTypesList_Saved();
            }
            private static bool __ContactTypesList_InvokeClosingEvent(global::LightSwitchApplication.ContactTypesList s)
            {
                bool cancel = false;
                s.ContactTypesList_Closing(ref cancel);
                return cancel;
            }
            private static void __ContactTypesList_InvokeCreated(global::LightSwitchApplication.ContactTypesList s)
            {
                s.ContactTypesList_Created();
            }
            private static void __ContactTypesList_InvokeActivated(global::LightSwitchApplication.ContactTypesList s)
            {
                s.ContactTypesList_Activated();
            }
            private static bool __ContactTypesList_InvokeSaveErrorEvent(global::LightSwitchApplication.ContactTypesList s, global::System.Exception ex)
            {
                bool handled = false;
                s.ContactTypesList_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.ContactTypesList.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.ContactTypesList.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ContactTypesSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.ContactTypesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes>.Data _ContactTypesSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes> ContactTypesSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes>)base.GetItem(global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties.ContactTypesSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes>.Entry
                    ContactTypesSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes>.Entry(
                        "ContactTypesSet",
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_Stub,
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_Validate,
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_CreateQuery,
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_SelectionChanged,
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_OnCollectionChanged,
                        global::LightSwitchApplication.ContactTypesList.DetailsClass.PropertySetProperties._ContactTypesSet_OnLoaded);
                private static void _ContactTypesSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContactTypesList.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ContactTypesList, global::LightSwitchApplication.ContactTypesList.DetailsClass, global::LightSwitchApplication.ContactTypes>.Data> c, global::LightSwitchApplication.ContactTypesList.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactTypesSet, sf);
                }
                private static void _ContactTypesSet_Validate(global::LightSwitchApplication.ContactTypesList s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.ContactTypesSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _ContactTypesSet_CreateQuery(global::LightSwitchApplication.ContactTypesList.DetailsClass d, object[] args)
                {
                    return d.ContactTypesSetQuery();
                }
                private static void _ContactTypesSet_SelectionChanged(global::LightSwitchApplication.ContactTypesList s)
                {
                    s.ContactTypesSet_SelectionChanged();
                }
                private static void _ContactTypesSet_OnCollectionChanged(global::LightSwitchApplication.ContactTypesList s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.ContactTypesSet_Changed(e);
                }
                private static void _ContactTypesSet_OnLoaded(global::LightSwitchApplication.ContactTypesList s, bool succeeded)
                {
                    s.ContactTypesSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CountryList
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CountryList() : base("LightSwitchApplication:CountryList")
        {
            global::LightSwitchApplication.CountryList.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CountryList CreateInstance()
        {
            return new global::LightSwitchApplication.CountryList(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountryList_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void CountriesSet_SelectionChanged();

        partial void CountriesSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountriesSet_Loaded(bool succeeded);

        /// <summary>
        /// Gets the CountriesSet visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Countries> CountriesSet
        {
            get
            {
                return global::LightSwitchApplication.CountryList.DetailsClass.GetValue(this, global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties.CountriesSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CountriesSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.CountryList.DetailsClass.PropertySet, global::LightSwitchApplication.CountryList.DetailsClass.CommandSet, global::LightSwitchApplication.CountryList.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties.CountriesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>.Entry
                __CountryListEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>.Entry(
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeSavingEvent,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeSavedEvent,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeClosingEvent,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeCreated,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeActivated,
                    global::LightSwitchApplication.CountryList.DetailsClass.__CountryList_InvokeSaveErrorEvent);
            private static void __CountryList_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CountryList s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CountryList_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CountryList_InvokeSavingEvent(global::LightSwitchApplication.CountryList s)
            {
                bool handled = false;
                s.CountryList_Saving(ref handled);
                return handled;
            }
            private static void __CountryList_InvokeSavedEvent(global::LightSwitchApplication.CountryList s)
            {
                s.CountryList_Saved();
            }
            private static bool __CountryList_InvokeClosingEvent(global::LightSwitchApplication.CountryList s)
            {
                bool cancel = false;
                s.CountryList_Closing(ref cancel);
                return cancel;
            }
            private static void __CountryList_InvokeCreated(global::LightSwitchApplication.CountryList s)
            {
                s.CountryList_Created();
            }
            private static void __CountryList_InvokeActivated(global::LightSwitchApplication.CountryList s)
            {
                s.CountryList_Activated();
            }
            private static bool __CountryList_InvokeSaveErrorEvent(global::LightSwitchApplication.CountryList s, global::System.Exception ex)
            {
                bool handled = false;
                s.CountryList_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CountryList.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CountryList.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CountryList.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CountriesSetQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.CountriesSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries>.Data _CountriesSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries> CountriesSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries>)base.GetItem(global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties.CountriesSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries>.Entry
                    CountriesSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries>.Entry(
                        "CountriesSet",
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_Stub,
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_Validate,
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_CreateQuery,
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_SelectionChanged,
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_OnCollectionChanged,
                        global::LightSwitchApplication.CountryList.DetailsClass.PropertySetProperties._CountriesSet_OnLoaded);
                private static void _CountriesSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CountryList.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CountryList, global::LightSwitchApplication.CountryList.DetailsClass, global::LightSwitchApplication.Countries>.Data> c, global::LightSwitchApplication.CountryList.DetailsClass d, object sf)
                {
                    c(d, ref d._CountriesSet, sf);
                }
                private static void _CountriesSet_Validate(global::LightSwitchApplication.CountryList s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.CountriesSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _CountriesSet_CreateQuery(global::LightSwitchApplication.CountryList.DetailsClass d, object[] args)
                {
                    return d.CountriesSetQuery();
                }
                private static void _CountriesSet_SelectionChanged(global::LightSwitchApplication.CountryList s)
                {
                    s.CountriesSet_SelectionChanged();
                }
                private static void _CountriesSet_OnCollectionChanged(global::LightSwitchApplication.CountryList s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.CountriesSet_Changed(e);
                }
                private static void _CountriesSet_OnLoaded(global::LightSwitchApplication.CountryList s, bool succeeded)
                {
                    s.CountriesSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CreateNewContacts
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewContacts() : base("LightSwitchApplication:CreateNewContacts")
        {
            global::LightSwitchApplication.CreateNewContacts.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewContacts CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewContacts(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewContacts_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void ContactsProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Contacts ContactsProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewContacts.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties.ContactsProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewContacts.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties.ContactsProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactsProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewContacts.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewContacts.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties.ContactsProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>.Entry
                __CreateNewContactsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeCreated,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeActivated,
                    global::LightSwitchApplication.CreateNewContacts.DetailsClass.__CreateNewContacts_InvokeSaveErrorEvent);
            private static void __CreateNewContacts_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewContacts s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewContacts_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewContacts_InvokeSavingEvent(global::LightSwitchApplication.CreateNewContacts s)
            {
                bool handled = false;
                s.CreateNewContacts_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewContacts_InvokeSavedEvent(global::LightSwitchApplication.CreateNewContacts s)
            {
                s.CreateNewContacts_Saved();
            }
            private static bool __CreateNewContacts_InvokeClosingEvent(global::LightSwitchApplication.CreateNewContacts s)
            {
                bool cancel = false;
                s.CreateNewContacts_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewContacts_InvokeCreated(global::LightSwitchApplication.CreateNewContacts s)
            {
                s.CreateNewContacts_Created();
            }
            private static void __CreateNewContacts_InvokeActivated(global::LightSwitchApplication.CreateNewContacts s)
            {
                s.CreateNewContacts_Activated();
            }
            private static bool __CreateNewContacts_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewContacts s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewContacts_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewContacts.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewContacts.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts>.Data _ContactsProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts> ContactsProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts>)base.GetItem(global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties.ContactsProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts>.Entry
                    ContactsProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts>.Entry(
                        "ContactsProperty",
                        false,
                        global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties._ContactsProperty_Stub,
                        global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties._ContactsProperty_Validate,
                        global::LightSwitchApplication.CreateNewContacts.DetailsClass.PropertySetProperties._ContactsProperty_OnValueChanged);
                private static void _ContactsProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewContacts, global::LightSwitchApplication.CreateNewContacts.DetailsClass, global::LightSwitchApplication.Contacts>.Data> c, global::LightSwitchApplication.CreateNewContacts.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactsProperty, sf);
                }
                private static void _ContactsProperty_Validate(global::LightSwitchApplication.CreateNewContacts s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.ContactsProperty_Validate(r);
                }
                private static void _ContactsProperty_OnValueChanged(global::LightSwitchApplication.CreateNewContacts s)
                {
                    s.ContactsProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
